---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  requirements_path: requirements.yml
  hosts: all

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: trusty64
    driver_config:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/trusty64

suites:
  - name: acls
  - name: atlas_configuration
  - name: custom_templates
  - name: default
  - name: dns
  - name: dynamic_binding
  - name: tls
  - name: tls_client
